CM-111: Upcasting and Downcasting in C#
CodeMazeBlog/CodeMazeGuides pull request #1012
Opened 2023-04-02 04:58 UTC by lasaetarubia

2023-04-02 07:04 UTC, PhilBroderick requested changes
Few changes required to the code and article.

2023-04-02 07:04 UTC, PhilBroderick commented on csharp-intermediate-topics/UpcastingAndDowncasting/UpcastingAndDowncasting/Program.cs
> +                var owl = args.Animal as Owl;
Likewise with pattern matching.

2023-04-02 08:36 UTC, lasaetarubia commented on csharp-intermediate-topics/UpcastingAndDowncasting/UpcastingAndDowncasting/Program.cs
> +            foreach (var ani in animals)
Had named it so because it interferes with the Downcasting code below otherwise. I am renaming it to "animalObj".

2023-04-02 12:28 UTC, PhilBroderick approved these changes

2023-04-06 09:25 UTC, PhilBroderick approved these changes

2023-04-06 09:25 UTC, merged