CM-45: Managed vs Unmanaged code (Garbage Collection)
CodeMazeBlog/CodeMazeGuides pull request #1107
Opened 2023-05-13 11:25 UTC by lasaetarubia

2023-05-14 09:27 UTC, PhilBroderick requested changes
Looks fine. Small formatting change. I'll get in touch with the team about the build errors.

2023-05-14 09:27 UTC, PhilBroderick commented on csharp-advanced-topics/ManagedVsUnmanagedCodeInCSharp/Tests/Test.cs
> +
Empty line here that should be removed.

2023-05-22 09:18 UTC, PhilBroderick requested changes
All the C++ code should be removed. Everything else looks fine.

2023-05-22 09:18 UTC, PhilBroderick commented on csharp-advanced-topics/ManagedVsUnmanagedCodeInCSharp/ManagedVsUnmanagedCodeInCSharp/ManagedMemoryManager.cs
> +            for (var i = 0; i < 100000; i++)
In the article, we are using 1,000,000, whereas here it is 10,000.

2023-05-22 10:22 UTC, lasaetarubia commented
retest this please

2023-05-23 16:19 UTC, PhilBroderick approved these changes

2023-06-01 13:49 UTC, merged