CM-756: Sending Mail With FluentMail in .NET
CodeMazeBlog/CodeMazeGuides pull request #1251
Opened 2023-07-14 06:23 UTC by muhammedsalimp

CM-756: Sending Mail With FluentMail in .NET

2023-07-14 21:58 UTC, jshergal commented on dotnet-client-libraries/FluentEmail/FluentEmailExample/Controllers/EmailController.cs
> +            var template = "Dear <b>@Model.Name</b>, </br>" +
We can use a raw string literal here

2023-07-15 06:54 UTC, PhilBroderick requested changes

2023-07-15 06:54 UTC, PhilBroderick commented on dotnet-client-libraries/FluentEmail/FluentEmailExample/Controllers/EmailController.cs
> +                , "FluentEmail Test email"
The commas should come after the previous parameter, and not on a newline. So for example:
```csharp
EmailMetadata emailMetadata = new("john.doe@gmail.com",
    "FluentEmail Test Email",
    "This is a test email from FluentEmail");

2023-07-15 06:54 UTC, PhilBroderick commented on dotnet-client-libraries/FluentEmail/FluentEmailExample/Controllers/EmailController.cs
> +            users.Add(user2);
We can define these users in the object initializer for the list instead of calling the `Add()` method.

2023-07-15 06:54 UTC, PhilBroderick commented on dotnet-client-libraries/FluentEmail/FluentEmailExample/Mytemplate.cshtml.cs
> +    public class MytemplateModel : PageModel
Following naming conventions, this should be `MyTemplateModel`.

2023-07-15 06:54 UTC, PhilBroderick commented on dotnet-client-libraries/FluentEmail/Tests/EmailControllerTests.cs
> +        public async Task WhenSendSingleEmailCalled_ThenSendInvokedAsync()
`Given_When_Then`.

2023-07-15 06:54 UTC, PhilBroderick commented on dotnet-client-libraries/FluentEmail/FluentEmailExample/Controllers/EmailController.cs
> +            string templateFile = $"{Directory.GetCurrentDirectory()}/Mytemplate.cshtml";
`var`.

2023-07-17 16:25 UTC, PhilBroderick requested changes
Couple more format issues.

2023-07-17 16:25 UTC, PhilBroderick commented on dotnet-client-libraries/FluentEmail/FluentEmailExample/Controllers/EmailController.cs
> +        };
This should be indented.

2023-07-18 14:58 UTC, PhilBroderick approved these changes

2023-07-20 07:58 UTC, merged