CM-744 : Optimistic Concurrency in ASP.NET Core Web API
CodeMazeBlog/CodeMazeGuides pull request #1335
Opened 2023-08-10 13:13 UTC by muhammedsalimp

CM-744 : Optimistic Concurrency in ASP.NET Core Web API

2023-08-12 13:22 UTC, mahrncic requested changes
Looks good, a couple of minor changes related to `var` keyword

2023-08-12 13:22 UTC, mahrncic commented on dotnet-efcore/OptimisticConcurrency/OptimisticConcurrency/Controllers/ProductsController.cs
> +            if (_context.Product == null)
I tend to use the `is` keyword where possible instead of `==`, just for the readability sake 😄

2023-08-12 13:22 UTC, mahrncic commented on dotnet-efcore/OptimisticConcurrency/OptimisticConcurrency/Model/Product.cs
> +﻿namespace OptimisticConcurrency.Model
Let's use file-scoped namespaces in all classes

2023-08-12 13:22 UTC, mahrncic commented on dotnet-efcore/OptimisticConcurrency/Tests/ProductsControllerTests.cs
> +
Remove this empty line

2023-08-12 13:22 UTC, mahrncic commented on dotnet-efcore/OptimisticConcurrency/Tests/ProductsControllerTests.cs
> +            List<Product> products = GetProducts();
Use `var` where possible

2023-08-12 13:22 UTC, mahrncic commented on dotnet-efcore/OptimisticConcurrency/Tests/ProductsControllerTests.cs
> +            List<Product> products = GetProducts();
`var`

2023-08-12 13:22 UTC, mahrncic commented on dotnet-efcore/OptimisticConcurrency/Tests/ProductsControllerTests.cs
> +            List<Product> products = GetProducts();
`var`

2023-08-12 13:22 UTC, mahrncic commented on dotnet-efcore/OptimisticConcurrency/Tests/ProductsControllerTests.cs
> +            List<Product> products = GetProducts();
`var`

2023-08-12 13:22 UTC, mahrncic commented on dotnet-efcore/OptimisticConcurrency/Tests/ProductsControllerTests.cs
> +            List<Product> products = GetProducts();
`var`

2023-08-12 13:22 UTC, mahrncic commented on dotnet-efcore/OptimisticConcurrency/Tests/ProductsControllerTests.cs
> +            List<Product> products = GetProducts();
`var`

2023-08-12 13:22 UTC, mahrncic commented on dotnet-efcore/OptimisticConcurrency/Tests/ProductsControllerTests.cs
> +            List<Product> products = GetProducts();
`var`

2023-08-15 14:53 UTC, mahrncic approved these changes

2023-08-17 20:12 UTC, jshergal commented on dotnet-efcore/OptimisticConcurrency/OptimisticConcurrency/Controllers/ProductsController.cs
> +        if (_context.Product == null)
For consistency in the code we should change these null checks to `is null` also.

2023-08-22 12:10 UTC, merged