CM 787:Getting Started With ASP.NET Core and MongoDB
CodeMazeBlog/CodeMazeGuides pull request #1362
Opened 2023-08-24 07:32 UTC by king-Alex-d-great

2023-08-24 09:18 UTC, jshergal commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Controllers/CourseController.cs
> +            return course is null ? NotFound() : Ok(course);
In most of the other null checks we are using `x == null`. We should seek to be consistent across the code with one version or the other. The `x is null` version is the more preferred style in modern .NET code, so I would recommend changing the others to match. Note that we can also use `x is not null` in the case where the check is `x != null`.

2023-08-24 09:28 UTC, jshergal commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/Test/StudentControllerUnitTest.cs
> +            Assert.Equal(students.Count, model.Count());
For consistency of the test, we should also verify that the returned students collection is the expected collection, i.e. that the students returned match what is expected.

2023-08-24 09:29 UTC, jshergal commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/Test/StudentControllerUnitTest.cs
> +
Extra blank line

2023-08-24 09:30 UTC, jshergal commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Controllers/StudentsController.cs
> +                student);
We should be using the `Student` returned by the `Create` call to populate the ID and student object data that are being included in the result.

2023-09-01 14:32 UTC, karimkod requested changes

2023-09-01 14:32 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Controllers/CourseController.cs
> +        private readonly ICourseService _CourseService;
this field doesn't following the naming convention of a private readonly field.

2023-09-01 14:32 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Program.cs
> +namespace GettingStartedASPNETMongoDB
We should switch to file-scoped namespaces for simplicity.

2023-09-01 14:32 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Program.cs
> +    public class Program
Why don't we use Top-level statement?

2023-09-01 14:32 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Properties/launchSettings.json
> +    },
We should only leave https profile.

2023-09-01 14:32 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Properties/launchSettings.json
> +      }
We should only leave https profile.

2023-09-01 14:32 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Interfaces/ICourseService.cs
> +        Task<Course> GetById(string id);
If this can return null when no Course is found, we should mark the return type as nullable with that Task<Course?>

2023-09-01 14:32 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Interfaces/IStudentService.cs
> +        Task<Student> GetById(string id);
If this can return null when no Course is found, we should mark the return type as nullable with that Task<Student?>

2023-09-01 14:32 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/Test/CourseControllerUnitTest.cs
> +        }
IN all the unit test method, we should have : 
(Given) some context
(When) some action is carried out
(Then) a particular set of observable consequences should obtain

Here, you are doing the action in the Given part and the context in the When part, it should be ther other way around, for example : 

GivenCreate_WhenSentCorrectData_ThenReturnCreatedStatus should be GivenCorrectData_WhenCreatingCourse_ThenReturnCreatedStatus.

This applies to the StudentControllerUnitTest as well.

2023-09-01 14:32 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Controllers/StudentsController.cs
> +            }
Here we don't need to check if the courses count is more than 0, we can just proceed with the execution of the logic, and it's also a good practice, to initialize the list to an empty list even if there are no courses, an empty list is better than null in this context. And we won't be needing an extra variable `var courseList` you can use `student.CourseList` directly.

2023-09-30 17:24 UTC, karimkod requested changes

2023-09-30 17:24 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Models/Course.cs
> +    public string Code { get; set; }
Properties that can be null should be marked as nullable, and properties that are not nullable, they should be set to null! .

2023-09-30 17:24 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Controllers/StudentsController.cs
> +        }
We don't need those as automatic validation is enabled.

2023-09-30 17:24 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Controllers/StudentsController.cs
> +        }
We don't need those as automatic validation is enabled.

2023-09-30 17:24 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/Test/CourseControllerUnitTest.cs
> +    }
We can inline these in the constructor directly.

2023-09-30 17:24 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/Test/StudentControllerUnitTest.cs
> +    }
We can inline these in the constructor directly.

2023-09-30 17:24 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/Test/StudentControllerUnitTest.cs
> +    public async Task GivenExisitingId_WhenUpdatingAStudent_ThenReturnNoContent()
Type in "Exisiting"

2023-09-30 17:24 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/Test/StudentControllerUnitTest.cs
> +    public async Task GivenExisitingId_WhenGettingAStudentById_ThenReturnStudentWithOkStatus()
Type in "Exisiting"

2023-10-14 18:27 UTC, karimkod requested changes

2023-10-14 18:27 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Program.cs
> +using MongoDB.Driver.Core.Configuration;
This is unused.

2023-10-14 18:29 UTC, karimkod submitted a review, later dismissed

2023-10-14 18:29 UTC, karimkod commented on aspnetcore-webapi/GettingStartedASPNETMongoDB/GettingStartedASPNETMongoDB/Controllers/StudentsController.cs
> +        }
@king-Alex-d-great  this wasn't addressed? can you check it please?

2023-12-04 15:00 UTC, CodeMazeBlog commented
retest this please

2023-12-04 15:05 UTC, closed without merging