CM-175:Blazor WebAssembly Ahead of Time Compilation (AoT)
CodeMazeBlog/CodeMazeGuides pull request #1416
Opened 2023-09-22 16:46 UTC by cjaynjoku

2023-09-25 05:29 UTC, asif-anwar commented
retest this please

2023-09-25 05:44 UTC, asif-anwar commented
retest this please

2023-09-25 06:21 UTC, CodeMazeBlog commented
Retest this please

2023-09-26 05:05 UTC, asif-anwar commented
retest this please

2023-09-26 05:09 UTC, asif-anwar commented
retest this please

2023-09-26 05:13 UTC, asif-anwar commented
retest this please

2023-09-26 05:20 UTC, asif-anwar commented
retest this please

2023-09-26 20:13 UTC, jshergal commented
@asif-anwar - the build is failing as there is a workload that needs to be installed in the CI build. I have reached out to the CodeMaze support to get that issue addressed. Sorry for the trouble.

2023-11-01 23:30 UTC, karimkod requested changes

2023-11-01 23:30 UTC, karimkod commented on blazor-features/BlazorWebAssemblyAheadOfTimeCompilation/Tests/PrimeNumberComponentTest.cs
> +    }
@cjaynjoku can you check if this test is succeeding locally in your machine?

2023-11-06 13:31 UTC, closed without merging