CM-747: Select a Dropdown Option Using Selenium WebDriver in C#
CodeMazeBlog/CodeMazeGuides pull request #1477
Opened 2023-10-19 17:56 UTC by semirteskeredzic

2023-11-05 23:58 UTC, karimkod requested changes

2023-11-05 23:58 UTC, karimkod commented on dotnet-testing/SelectDropdownOptionUsingSeleniumWebDriver/SelectDropdownOptionUsingSeleniumWebDriver/Properties/launchSettings.json
> +      }
This can be removed (only keep "https")

2023-11-05 23:58 UTC, karimkod commented on dotnet-testing/SelectDropdownOptionUsingSeleniumWebDriver/SelectDropdownOptionUsingSeleniumWebDriver/Properties/launchSettings.json
> +    },
This can be removed (only keep "https")

2023-11-05 23:58 UTC, karimkod commented on dotnet-testing/SelectDropdownOptionUsingSeleniumWebDriver/SelectDropdownOptionUsingSeleniumWebDriverTests/LiveTest.cs
Comments are not needed.

2023-11-13 00:44 UTC, karimkod commented
Hello @semirteskeredzic,
I am not able to run the test locally, is there anything specific I should do before running the test, apart from running the app? 
```
OpenQA.Selenium.WebDriverException: unknown error: result.webdriverValue.value list is missing or empty in Runtime.callFunctionOn response
```

2023-11-13 09:37 UTC, semirteskeredzic commented
Hi @karimkod , the issue probably lies in the discrepencies of the drivers e.g Google Chrome installed on the machine is probably 119.*.*.* while ChromeDriver is 118.*.*.*

The same applies to Edge. You can also change VersionResolveStrategy of the browserVersion from Latest to MatchingBrowser.

For reference: [https://stackoverflow.com/questions/77428873/im-getting-this-error-unknown-error-result-webdrivervalue-value-list-is-missin](https://stackoverflow.com/questions/77428873/im-getting-this-error-unknown-error-result-webdrivervalue-value-list-is-missin)

2023-11-15 12:54 UTC, semirteskeredzic commented
@karimkod , I've retested on my M1 machine and can't replicate the issue.
Google Chrome version was 116. and chromewebdriver was 118. I updated the Chrome on my machine to 119 and still couldn't replicate the issue.
Then I updated all packages to latest versions and still all tests pass. I then moved to Win11 machine and again weren't able to replicate the issue. To be on the safe side I've updated the edgewebdriver and added the driver for windows machines.
Please pull the latest code, build, run and test and let me know if you continue to have issue.

2023-11-19 21:07 UTC, karimkod commented
Thanks @semirteskeredzic, it's seems like the issue is fixed.

2023-12-03 14:19 UTC, karimkod submitted a review, later dismissed

2023-12-05 10:57 UTC, merged