CM-75: Rest vs WebSockets In C#
CodeMazeBlog/CodeMazeGuides pull request #1517
Opened 2023-11-07 14:22 UTC by acha-r

2023-11-09 17:15 UTC, mahrncic requested changes

2023-11-09 17:15 UTC, mahrncic commented on aspnetcore-webapi/RestVsWebSocket/RestVsWebSocket/Controllers/TaskController.cs
> +namespace RestVsWebSocket.Controllers
Use file-scoped namespaces everywhere

2023-11-09 17:15 UTC, mahrncic commented on aspnetcore-webapi/RestVsWebSocket/Tests/AddTaskTest.cs
> +namespace Tests
File-scoped

2023-11-09 17:15 UTC, mahrncic commented on aspnetcore-webapi/RestVsWebSocket/RestVsWebSocket/Controllers/TaskController.cs
> +        public IList<string> _tasks;
Why do we have an underscore inside the name `_tasks` if the field is public?

2023-11-12 15:12 UTC, mahrncic requested changes
Why there is no console app as a part of this PR?

2023-11-12 15:18 UTC, acha-r commented on aspnetcore-webapi/RestVsWebSocket/RestVsWebSocket/Controllers/TaskController.cs
> +            return BadRequest("Enter valid data");
the Jenkins build was failing because of it.

2023-11-12 15:19 UTC, acha-r commented
> Why there is no console app as a part of this PR?

The Jenkins build was failing because of it

2023-11-13 17:53 UTC, mahrncic requested changes
`Recieve` -> `Receive`

2023-11-13 17:53 UTC, mahrncic commented on aspnetcore-webapi/RestVsWebSocket/Client/Program.cs
> +var recieveTask = Task.Run(async () =>
As stated earlier on the API project, this should be called `receiveTask` instead of `recieveTask`

2023-11-13 17:53 UTC, mahrncic commented on aspnetcore-webapi/RestVsWebSocket/Client/Program.cs
> +        Console.WriteLine("Recieved: " + message);
Same here, `Received` instead of `Recieved`

2023-11-15 20:24 UTC, mahrncic approved these changes

2023-11-20 15:44 UTC, merged