CM-831 - Broker Architectural Pattern in C#
CodeMazeBlog/CodeMazeGuides pull request #1527
Opened 2023-11-16 15:32 UTC by muhammedsalimp

CM-831 -Broker Architectural Pattern in C#

2023-11-19 09:23 UTC, mahrncic requested changes
Great job in overall, a couple of changes are needed on most of the files and projects:

- use .NET 8
- use file-scoped namespaces
- use `var` where possible
- always add a blank line before a `return` statement where possible

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/EventBroker/Broker.cs
> +namespace EventBroker
Let's use file-scoped namespaces everywhere

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/EventBroker/EventBroker.csproj
> +    <TargetFramework>net7.0</TargetFramework>
.NET 8 is out, so let's use it 😄

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/EventBroker/Interfaces/IBroker.cs
> +﻿namespace EventBroker.Interfaces
file-scoped

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/EventBroker/Message.cs
> +
Remove this blank line

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagePublisher1/MessagePublisher1.cs
> +            string message = new($"Message from sender for topic:{topicName} at {currentDateTime}!");
Use `var`

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagePublisher1/MessagePublisher1.csproj
> +    <TargetFramework>net7.0</TargetFramework>
.NET 8

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagePublisher1/Program.cs
> +            HostApplicationBuilder builder = Host.CreateApplicationBuilder();
`var`

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagePublisher2/MessagePublisher2.cs
> +            string message = new($"Message from sender for topic:{topicName} at {currentDateTime}!");
`var`

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagePublisher2/MessagePublisher2.csproj
> +    <TargetFramework>net7.0</TargetFramework>
.NET 8

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagePublisher2/Program.cs
> +            HostApplicationBuilder builder = Host.CreateApplicationBuilder();
`var`

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagePublisherSubscriberTests/MessagePublisherSubscriberTests.csproj
> +    <TargetFramework>net7.0</TargetFramework>
.NET 8

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessageReceiver/MessageReceiverApp.csproj
> +    <TargetFramework>net7.0</TargetFramework>
.NET 8

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessageReceiver/Program.cs
> +            HostApplicationBuilder builder = Host.CreateApplicationBuilder();
`var`

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessageSender/MessageSender.cs
> +            string message = new($"Message from sender at {currentDateTime}!");
`var`

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessageSender/MessageSenderApp.csproj
> +    <TargetFramework>net7.0</TargetFramework>
.NET 8

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessageSender/Program.cs
> +            HostApplicationBuilder builder = Host.CreateApplicationBuilder();
`var`

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagingService/MessageService.cs
> +            return client;
The `return` statement should always have a blank line before it. Make sure to apply it where possible.

2023-11-19 09:23 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagingService/MessageService.cs
> +            return Task.CompletedTask;
Blank line before `return`

2023-11-23 21:40 UTC, mahrncic requested changes
A couple of blank lines and one non file-scoped namespace left

2023-11-23 21:40 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagePublisher2/Program.cs
> +
This blank line should be removed

2023-11-23 21:40 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessagePublisherSubscriberTests/MessagePublisherSubscriberTests.cs
> +{
File-scoped namespace should be used

2023-11-23 21:40 UTC, mahrncic commented on csharp-architectural-patterns/BrokerPattern/MessageSubscriber3/Program.cs
> +
Remove this blank line

2023-11-25 10:31 UTC, mahrncic approved these changes

2023-12-22 18:07 UTC, mahrncic approved these changes

2023-12-25 15:32 UTC, jshergal commented on csharp-architectural-patterns/BrokerPattern/MessagingService/MessageService.cs
> +    static ServiceBusClient ServiceBusClient => CreateClient();
This should be `private static readonly` and the `=>` should be just `=`. As it is written now we are still creating a new client for every access of `ServiceBusClient`

2023-12-27 15:05 UTC, closed without merging