Added code for the application including tests
CodeMazeBlog/CodeMazeGuides pull request #1861
Opened 2024-03-03 22:53 UTC by semirteskeredzic

2024-03-06 18:31 UTC, sahebagarwal-codemaze requested changes

2024-03-06 18:31 UTC, sahebagarwal-codemaze commented on strings-csharp/CountNumberOfVowelsInString/CountNumberOfVowelsInString/VowelCounters.cs
> +        string sentence = "In the vast expanse of the universe, countless galaxies swirl in a cosmic dance, each telling a unique story of creation and destruction.";
Use var instead of explicit datatype "string"

2024-03-06 18:31 UTC, sahebagarwal-codemaze commented on strings-csharp/CountNumberOfVowelsInString/CountNumberOfVowelsInString/VowelCounters.cs
> +        int total = 0;
Use var instead of explicit datatype "int"
Same comments throughout the solution

2024-03-06 18:31 UTC, sahebagarwal-codemaze commented on strings-csharp/CountNumberOfVowelsInString/CountNumberOfVowelsInString/VowelCounters.cs
> +        foreach (char c in sentence)
use curly bracket {} for both foreach and if block

2024-03-06 18:31 UTC, sahebagarwal-codemaze commented on strings-csharp/CountNumberOfVowelsInString/CountNumberOfVowelsInString/VowelCounters.cs
> +                default: continue;
use break in default case, move it in the next line

2024-03-06 18:31 UTC, sahebagarwal-codemaze commented on strings-csharp/CountNumberOfVowelsInString/CountNumberOfVowelsInString/VowelCounters.cs
> +        int total = Regex.Matches(sentence, @"[AEIOUaeiou]").Count;
We can use IgnoreCase in the regex as below:
int total = Regex.Matches(sentence, @"[AEIOU]", RegexOptions.IgnoreCase).Count;

2024-03-27 16:28 UTC, sahebagarwal-codemaze commented on strings-csharp/CountNumberOfVowelsInString/CountNumberOfVowelsInString/VowelCountersHelperMethods.cs
This file is unused, we can remove it.

2024-03-27 16:28 UTC, sahebagarwal-codemaze commented on strings-csharp/CountNumberOfVowelsInString/CountNumberOfVowelsInString/VowelCounters.cs
> +    public static int CountVowelsUsingSwitchStatement(string sentence)
For this method also, instead of string we can have it as ReadOnlySpan<char> sentence

2024-03-27 20:37 UTC, CodeMazeBlog commented
retest this please

2024-04-28 04:52 UTC, merged