CM-609:Value vs Reference Types in C#
CodeMazeBlog/CodeMazeGuides pull request #727
Opened 2022-11-23 16:10 UTC by alfredkakuli

2022-11-28 16:31 UTC, mahrncic requested changes

2022-11-28 18:44 UTC, alfredkakuli commented on csharp-basic-topics/ValueVsReferenceTypes/ValueVsReferenceTypes/Program.cs
> +        CarModel carModel1 = new()
hello, thanks.
The idea of car2 and Model1 was to explicitly differentiate between the first and second instances before and after mutation. About the extra CarModel class, I was thinking of a typical real-world scenario where a car has a bunch of properties with persistence.
Once again thank you, I will update as per your guidelines.

2022-12-30 18:06 UTC, mahrncic requested changes
Good job on the first batch of changes, I added a couple of more :)

Also, please make sure to upgrade the solution/project to .NET 7

2022-12-30 18:06 UTC, mahrncic commented on csharp-basic-topics/ValueVsReferenceTypes/ValueVsReferenceTypes/Car.cs
> +        public string ChangeCarModel( string newModel)
Remove the blank space before the `string` keyword in the method parameters space.

2023-01-10 16:15 UTC, mahrncic requested changes

2023-01-10 16:15 UTC, mahrncic commented on csharp-basic-topics/ValueVsReferenceTypes/ValueVsReferenceTypes/Car.cs
> +        public Car(string modelName)=> ModelName = modelName;
Why do we initialize the value of the `ModelName` setter in the constructor?

2023-01-10 16:15 UTC, mahrncic commented on csharp-basic-topics/ValueVsReferenceTypes/ValueVsReferenceTypes/WorkingDaysCalculator.cs
> +        public WorkingDaysCalculator() => DaysOfTheWeek = 7;
Again, why do we initialize the value of the `DaysOfTheWeek` setter in the constructor, and not on the setter directly?

2023-01-17 00:04 UTC, closed without merging