CM-619: IEnumerable, ICollection, IList and List - Which One to Use?
CodeMazeBlog/CodeMazeGuides pull request #814
Opened 2023-01-21 07:00 UTC by OldPen16

2023-01-28 00:02 UTC, karimkod requested changes

2023-01-28 00:02 UTC, karimkod commented on collections-csharp/IEnumeralbleVsICollectionVsIListVsList/Tests/Test.cs
> +    public class Tests
Both The **file** and the class that contains the type should end with *UnitTest so I suggest to change this file to CollectionInterfacesUnitTest os something similar.

2023-01-29 13:59 UTC, OldPen16 commented on collections-csharp/IEnumeralbleVsICollectionVsIListVsList/IEnumeralbleVsICollectionVsIListVsList/Program.cs
> +            Console.WriteLine($"IList with List input:{ils.CountSpecialCharacters(specialCharacter)}\nIList with Array input:{ils.CountSpecialCharactersArray(arrayOfSpecialCharacter)}");
Please can you add the article link here and point to the specific example?

2023-01-29 14:03 UTC, OldPen16 commented on collections-csharp/IEnumeralbleVsICollectionVsIListVsList/IEnumeralbleVsICollectionVsIListVsList/ImplementationOfIEnumerable.cs
> +        }
I didn't find a yield keyword example in your shared links. Please can you share the link here and point it for my reference

2023-01-29 16:36 UTC, karimkod commented on collections-csharp/IEnumeralbleVsICollectionVsIListVsList/IEnumeralbleVsICollectionVsIListVsList/Program.cs
> +            Console.WriteLine($"IList with List input:{ils.CountSpecialCharacters(specialCharacter)}\nIList with Array input:{ils.CountSpecialCharactersArray(arrayOfSpecialCharacter)}");
Hello @OldPen16, sorry for I wasn't clear enough. 
I meant the article review and it's the point 6.b (just search in the docs 6.b and you will find my point about the array example).

2023-01-29 16:37 UTC, karimkod commented on collections-csharp/IEnumeralbleVsICollectionVsIListVsList/IEnumeralbleVsICollectionVsIListVsList/ImplementationOfIEnumerable.cs
> +        }
The example of yield is in the article review docs and it's the point 2.a

2023-02-06 19:05 UTC, karimkod commented
Hey @OldPen16,

1 - I don't see any tests in the test folder was this intentional or you missed to commit the test. 
It's important to have the test to verify the wanted behaviour of the code in the article. 

2 - There is a typo in all the code types : IEnumeralble should be IEnumerable.

2023-02-10 17:53 UTC, closed without merging