CM-397: Delete Elements from an Array.
CodeMazeBlog/CodeMazeGuides pull request #921
Opened 2023-02-27 18:39 UTC by KonstantinosP7

I committed the branch regarding the CM-397 issue. Please for your review.

2023-02-28 17:02 UTC, PhilBroderick requested changes
Mostly formatting changes are required.

2023-02-28 17:02 UTC, PhilBroderick commented on collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray.Benchmark/DeleteElementsFromArrayBenchmark.cs
> +                if (_myArray[i] != _key) {
Again, move `{` onto a new line.

2023-02-28 17:02 UTC, PhilBroderick commented on collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray.Benchmark/DeleteElementsFromArrayBenchmark.cs
> +            Random rnd = new Random();
Can use `var rnd` here.

2023-02-28 17:02 UTC, PhilBroderick commented on collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray/Methods/DeleteWithFindAllMethod.cs
> +    public static partial class Methods {
Formatting.

2023-02-28 17:02 UTC, PhilBroderick commented on collections-arrays/DeleteElementsFromArray/DeleteElementsFromArray/Methods/DeleteWithLoopMethod.cs
> +    public static partial class Methods {
Likewise.

2023-03-04 19:04 UTC, KonstantinosP7 commented
Hello Phil, 
I checked through every file of the solution and fixed this formatting issue. Fyi, it was created because I used the shortcut formatting of vs.

2023-03-05 07:33 UTC, PhilBroderick requested changes
Just one further change that'll require some changes in the article.

2023-03-05 16:39 UTC, PhilBroderick approved these changes

2023-03-19 08:58 UTC, PhilBroderick approved these changes

2023-03-22 11:18 UTC, merged